pages/urls.py
from django.urls import path
from . import views

# add namespace for links
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index') 
     
]

polls/urls.py
from django.urls import path
from . import views

# add namespace for links
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'), # "/polls"
    path('<int:question_id>/', views.detail, name='detail'), 
    path('<int:question_id>/results', views.results, name='results'), 
    path('<int:question_id>/vote', views.vote, name='vote'), 
    path('resultsdata/<str:obj>', views.resultsData, name='resultsData') 
]

pypoll/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('polls/', include('polls.urls')), # "include" points to /polls/url.py
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# question and choice model to point to their respective db table

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pages/views.py
from django.shortcuts import render

def index(request):
    return render(request,'pages/index.html')

polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question

# Get questions and display them
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list' : latest_question_list}
    # this loads the template
    # context allows access to data
    return render(request, 'polls/index.html', context)

# Show specific question and its choices
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Poll question with that id could not be found.")
    return render(request, 'polls/detail.html', {'question': question})

# Get question and displays vote results
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

# Vote for a choice
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try: 
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay vote form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'You did not select an option.'
        })

    else: 
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def resultsData(request, obj):
    voteData = []

    question = Question.objects.get(id=obj)
    votes = question.choice_set.all()

    for i in votes: 
        voteData.append({i.choice_text: i.votes})

    return JsonResponse(voteData, safe=False)

templates/base.html
<!DOCTYPE html>

<html class="no-js"> 
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <title>PyPolls {% block title %}{%endblock %}</title>
    </head>
    <body>
        {% include 'partials/_navbar.html' %}
        <div class='container'>
            <div class='col-md-6 m-auto'>
                {% block content %}{% endblock %}
            </div>
        </div>
        
    </body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class='card text-center'>
    <div class='card-body'>
        <h1>This is PyPoll</h1>
        <p>A Dorky Questionaire Game</p>
        <a class='btn btn-dark' href="{% url 'polls:index' %}">Take a Poll</a>
    </div>
</div>
{% endblock %}

templates/partials/_navbar.html
<nav style='background: #ecf75c' class='navbar navbar mb-4'>
    <div class='container'>
        <a class='navbar-brand' href='/'>PyPoll</a>
    </div>
</nav>

templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'polls:index' %}" class='btn btn-secondary btn-sm mb-3'>Return</a>
    <h1 class='text-center mb-3'>{{ question.question_text }}</h1>

    {% if error_message %}
    <p class='alert alert-danger'>
        <strong>{{ error_message }}</strong>
    </p>
    {% endif %}

        <form action="{% url 'polls:vote' question.id %}" method='post'>
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
            <div class='form-check'>
                <input
                    type='radio'
                    name='choice'
                    class='form-check-input'
                    id='choice{{ forloop.counter }}'
                    value='{{ choice.id }}'
                />
                <label for='choice{{ forloop.counter}}'>{{ choice.choice_text }}</label>
            </div>
            {% endfor %}
            <input type='submit' value='Vote' class='btn btn-success btn-lg btn-block mt-4'/>
        </form>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class='text-center mb-3'>Poll Questions</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class='card mb-3'>
                <div class='card-body'>
                    <p> {{ question.question_text }}</p>
                    <a href="{% url 'polls:detail' question.id %}" class='btn btn-primary btn-sm'>Vote</a>
                    <a href="{% url 'polls:results' question.id %}" class='btn btn-secondary btn-sm'>See Results</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No current polls open</p>
    {% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}

<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>
<div  style='margin-bottom: 40px;'>
	<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back</a>
	<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote</a>
</div>

<section >
	<ul class="list-group mb-5">
		{% for choice in question.choice_set.all %}
		<li class="list-group-item">
			{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
		</li>
		{% endfor %}
	</ul>

	<div id='pollChart'></div>
	<script>
		var state = {
			'items': [],
			'values': []
		}
		var objId = '{{question.id}}'

		$.ajax({
			method: 'GET',
			url:  `/polls/resultsdata/${objId}`,
			success: function(res){
				res.map(item=> {
					let key = Object.keys(item)
					let val = Object.values(item)
					state.items.push(key[0])
					state.values.push(val[0])
				})
				buildChart()
			}
		})

		function buildChart(){
			var chartData = {
				"type":'bar',
				'scale-x': {
					'values': state.items
				},
				'series': [{
					'values': state.values,
					backgroundColor: '#8ee9de'
				}]
			}
			zingchart.render({
				id: 'pollChart',
				data: chartData,
			})
		}
		

	</script>
</section>




{% endblock %}